version: "3.9"
services:
  db:
    image: postgres:13.3
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postal
      - PGDATA=/var/lib/postgresql/data
#    volumes:
#      - ./db/postal/data:/var/lib/postgresql/data
    ports:
      - 5433:5433
    restart: always
  app:
    image: postal
    container_name: postal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postal
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 80:8080
    depends_on:
      - db